### ISSUE TITLE
코드 리뷰 부탁드립니다!

### ISSUE THREAD

**Issue by imhjnoh** [imhjnoh/magazine#1]
- 이번에는 mui를 사용하면서 이전보다 코드가 지저분해진 느낌이 드는데, 혹시 개선할 수 있는 방법이 있을까요?

**Comment by zubetcha** [comment]
희정님 안녕하세요!

말씀해주신 부분은 mui에서 제공하는 컴포넌트 사용 방법이기 때문에 컴포넌트에 넘겨주는 props가 많아지는 건 어쩔 수 없을 것 같습니다 ㅠㅠ
그래도 코드 줄을 줄이고 싶다면 SignUp 페이지의 TextField 컴포넌트에 필요한 props처럼 여러번 반복되는 props들을 유동적으로 생성해주는 함수를 만들어서 컴포넌트에는 스프레드 연산자의 형태로 props를 넘기는 방법이 있을 것 같습니다!

<img width="577" alt="스크린샷 2022-07-23 오후 10 25 18" src="https://user-images.githubusercontent.com/91620721/180607107-1cac97aa-7a10-4bf7-bbd0-0104fd4b1b27.png">

수고 많으셨습니다! 👏🏻

**Comment by imhjnoh** [comment]
감사합니다!!
